### ISSUE TITLE
Wrong InnoDB check

### ISSUE THREAD

**Issue by artoodetoo** [parpalak/s2#1]
Existing InnoDB check doesn't work on install when we have MariaDB on back-end. Perhaps it is also failing on MySQL 5.5+ but I haven't such instance to test. 

To fix error you can replace
```sql
SHOW VARIABLES LIKE 'have_innodb'
```
to
```sql
SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB'
```
as described here: https://fluxbb.org/development/core/tickets/1078/

Thank you.

**Comment by parpalak** [comment]
Hi, @artoodetoo. Thanks for reporting. I'm gonna test this fix, but not right now :)

**Comment by parpalak** [comment]
I assume it is outdated. In current development version (S2 2.0-dev) InnoDB is required for MySQL/MariaDB. BTW, I've explained in a blog post what is the current development version: https://parpalak.com/blog/2023/08/25/thoughts_on_S2
