### ISSUE TITLE
Время старта

### ISSUE THREAD

**Issue by MioVisman** [parpalak/s2#3]
https://github.com/parpalak/s2/blob/77453533951312ab8728f5d9f08bfc495a130aff/_include/common.php#L14

Предлагаю заменить
`$s2_start = microtime(true);`
на
`$s2_start = $_SERVER['REQUEST_TIME_FLOAT'] ?? microtime(true);`
для большей реалистичности.

**Comment by parpalak** [comment]
Зависит от того, что мы хотим измерять. Тут хорошо описана разница: https://stackoverflow.com/questions/55885892/can-we-use-serverrequest-time-float-to-get-a-reliable-process-time

Не совсем понятно, какой именно реалистичности хотим добиться этим изменением? Если смотреть со стороны посетителя, то ни один из вариантов не будет отражать реальное время ожидания ответа. На пользовательский опыт влияют и сетевые задержки (latency), и время на установку https-соединения, и время скачивания ответа, css- и js-файлов, и рендеринг всего этого дела в браузере.

Сейчас $s2_start = microtime(true); может пригодиться для двух вещей. Во-первых, отладка разработчиками расширений и владельцами сайтов. Во-вторых, "маркетинг": посмотрите, как круто, страница сгенерировалась всего за 20 миллисекунд. Это число можно сравнивать с другими движками. При этом конечный пользователь, конечно, этот ответ получит минимум раз в 10 медленнее.

**Comment by MioVisman** [comment]
>Во-вторых, "маркетинг"

Все понятно. Обман, кругом обман.
