### ISSUE TITLE
MySQL error when installing on MySQL<5.7

### ISSUE THREAD

**Issue by draugmot** [parpalak/s2#4]
CMS uses VARCHAR(255) several times and VARCHAR(200), while MySQL 5.6 and less hasn't got enough space for these with utf8mb4, quick fix is setting all of them to VARCHAR(191)

**Comment by parpalak** [comment]
MySQL 5.6 was released 11 years ago, and its support ended over 3 years ago. It's hard to believe that S2 has a user with such an old database. If true, I can make the necessary changes.

**Comment by draugmot** [comment]
Here I am but I'm a bit of an idiot, it's MariaDB 5.5.68, not MySQL 5.5, so quite old, but not that ancient, while the problem is most likely the same.

If there's no one else with this problem, I don't know if it's worth fixing ) I don't think these 64 characters will cause any trouble later

**Comment by parpalak** [comment]
Well, I've adjusted the length of some columns: https://github.com/parpalak/s2/commit/2fb9382645e793976a823fce906c7da85e61b971

But that is not the only issue with old MySQL versions. There is also a lack of NOWAIT SQL keyword in the queue for background jobs: https://github.com/parpalak/s2/blob/eedd7c30646b994d6f656c3cf35319761c9d6d46/_include/src/Queue/QueueConsumer.php#L44
Background jobs are now used for thumbnails generating in search results page and updating the recommendations cache.
